package sre.agent.agents;

import com.google.adk.agents.LlmAgent;
import com.google.adk.tools.mcp.McpToolset;
import com.google.adk.tools.mcp.StdioServerParameters;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GitHubPrAgent {

    public static LlmAgent create() {

        String token = System.getProperty("GITHUB_TOKEN");
        if (token == null) {
            token = System.getenv("GITHUB_TOKEN");
        }

        String repo = System.getProperty("GITHUB_REPO");
        if (repo == null) {
            repo = System.getenv("GITHUB_REPO");
        }

        Map<String, String> env = new HashMap<>();
        env.put("GITHUB_PERSONAL_ACCESS_TOKEN", token);

        StdioServerParameters serverParams =
                StdioServerParameters.builder()
                        .command("npx")
                        .args(List.of(
                                "-y",
                                "@modelcontextprotocol/server-github"
                        ))
                        .env(env)
                        .build();

        McpToolset mcpToolset = new McpToolset(
                serverParams.toServerParameters()
        );

        String instruction = String.format("""
            You are a GitHub PR automation agent
            for the IncidentIQ SRE system.
            
            You will receive an errorType and a
            full incident report containing root
            cause and fix suggestions.
            
            Follow these steps EXACTLY:
            
            STEP 1 — Create a branch:
            Branch name:
            fix/incidentiq-[errorType]
            Use create_branch tool.
            Base branch: main
            Repository: %s
            
            STEP 2 — Find the affected file:
            Look at the incident report for:
            - Class names mentioned
            - Stack trace file references
            - Method names
            
            The error service code is in:
            error-service/src/main/java/sre/errorservice/
            
            Use search_code tool to find the
            relevant Java file in repository: %s
            
            Search for the class name from the
            stack trace. For example:
            - NullPointerException → search "ErrorController"
            - OutOfMemoryError → search "OrderProcessor"
            - StackOverflowError → search "CategoryService"
            
            STEP 3 — Read the file:
            Use get_file_contents to read the
            full content of the file found.
            Repository: %s
            
            STEP 4 — Apply the fix:
            Based on the fix suggestion in the
            incident report:
            - Add null checks for NullPointerException
            - Add memory limits for OutOfMemoryError
            - Add recursion guards for StackOverflow
            - Add timeout handling for SocketTimeout
            - Add input validation for IllegalArgument
            - Add bounds checks for ArrayIndexOutOfBounds
            
            Make the minimal code change needed.
            Keep all existing code intact.
            Only add the fix — do not rewrite the file.
            
            Use create_or_update_file to save
            the updated file.
            Commit message:
            fix: [errorType] - auto-fix by IncidentIQ
            Branch: fix/incidentiq-[errorType]
            Repository: %s
            
            STEP 5 — Create a Pull Request:
            Title:
            [IncidentIQ] Fix: [errorType]
            
            Body:
            ## 🤖 Auto-Fix by IncidentIQ
            
            ### Error
            [errorType]
            
            ### Root Cause
            [from incident report]
            
            ### Fix Applied
            [describe what code change was made]
            
            ### Full Incident Report
            [paste full report]
            
            ---
            *Generated by IncidentIQ SRE Agent*
            *Please review before merging*
            
            Base: main
            Head: fix/incidentiq-[errorType]
            Repository: %s
            
            STEP 6 — Return ONLY these lines:
            PR_URL: <full github pr url>
            PR_NUMBER: <number>
            BRANCH: <branch name>
            FILE: <file that was changed>
            
            CRITICAL RULES:
            - Read errorType and report from
              the user message directly
            - Do NOT call utcnow or time tools
            - Do NOT skip any step
            - Do NOT ask questions
            - If file not found, still create PR
              with fixes/[errorType]-fix.md instead
            - Start with STEP 1 immediately
            """,
                repo, repo, repo, repo, repo
        );

        return LlmAgent.builder()
                .name("github_pr_agent")
                .model("gemini-2.5-flash")
                .description(
                        "Creates GitHub PRs with actual " +
                                "code fixes from incident reports"
                )
                .instruction(instruction)
                .tools(List.of(mcpToolset))
                .outputKey("pr_result")
                .build();
    }
}